name: kanban
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  animations: ^2.0.11
  appflowy_board: ^0.1.2
  bloc: ^8.1.4
  connectivity_plus: ^6.0.3
  dartz: ^0.10.1
  dio: ^5.4.3+1
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  equatable: ^2.0.5
  figma_squircle: ^0.5.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5

  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  http_parser: ^4.0.2
  intl: ^0.19.0
  logger: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.3
  shimmer: ^3.0.0

  # flutter_gen: any
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
